"""private messages2

Revision ID: 047311fa156d
Revises: a95ff6425904
Create Date: 2019-07-11 17:58:12.784921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047311fa156d'
down_revision = 'a95ff6425904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
